### ISSUE TITLE
Unaligned timetable cells

### ISSUE THREAD

**Issue by yangshun** [li-kai/modify#4]
<img width="1434" alt="screen shot 2016-09-07 at 11 15 08 pm" src="https://cloud.githubusercontent.com/assets/1315101/18317540/19c430c0-7551-11e6-8c0d-6d73634e15c6.png">

Hey @li-kai , not sure why but recently I realized that the alignment for the table cells can be off sometimes (attached in the screenshot).

My recommendation is that don't use a border when the `display` is `flex` as it makes it harder to compute the width of cells (such as 200.4%). Instead, have two superimposing layers, one for the grid/lines, the other for the cells. You can check out my approach here: https://github.com/yangshun/nusmods-v3

**Comment by li-kai** [comment]
@yangshun I know about this error but I couldn't reproduce it, even on the same browser version. Thanks for the suggestion, I'll take a look.

I've had thought about using two layers. The problem comes with modules that are really wordy and break the standard height. The rows wouldn't be consistent with the modules/cells any more. One example would be a half hour slot with week 1 - 13 (Can't remember the code any more)
